name: RadiationZone
version: 2.0
author: EternalRat
depend: [ AdditionsAPI ]
api-version: 1.13
main: fr.eter.radiationzone.RadiationZone
permissions:
   lead:
      description: Made for the owner
      default: op
commands:
  sethome:
    description: Set an home somewhere 
  home:
    description: Go to your home or take a look at the list
  delhome:
    description: Delete an home that you have
  tpa:
    description: TP yourself to someone
  tpaccept:
    description: Accept the TPA
  tpdecline:
    description: Refuse the TPA
  seeplayers:
    description: See the list of connected players
    permission: lead
  seeinventory:
    description: See the inventory of a player
    permission: lead