name: RadiationZone
version: 1.0
author: EternalRat
main: fr.eter.radiationzone.RadiationZone
commands:
  sethome:
    description: Set an home somewhere 
  home:
    description: Go to your home or take a look at the list
  delhome:
    description: Delete an home that you have
  tpa:
    description: TP yourself to someone
  tpaccept:
    description: Accept the TPA
  tpdecline:
    description: Refuse the TPA